# Generated by Django 5.2.13 on 2026-04-16 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('view', 'Consultation'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('search', 'Recherche'), ('filter', 'Filtrage')], max_length=20, verbose_name='Action')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique utilisateur',
                'verbose_name_plural': 'Historiques utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
