# Generated by Django 5.2.13 on 2026-05-07 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='Session ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('response', models.TextField(verbose_name='Réponse')),
                ('is_feedback', models.BooleanField(default=False, verbose_name='Est un feedback')),
                ('feedback_type', models.CharField(blank=True, choices=[('complaint', 'Plainte'), ('suggestion', 'Suggestion'), ('question', 'Question'), ('other', 'Autre')], max_length=20, null=True, verbose_name='Type de feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Conversation chatbot',
                'verbose_name_plural': 'Conversations chatbot',
                'ordering': ['-created_at'],
            },
        ),
    ]
